### ISSUE TITLE
StableLM Alpha Testing Issue

### ISSUE THREAD

**Issue by MarkSchmidty** [AUGMXNT/llm-experiments#1]
@lhl could you shed some light on your testing regimen in this StableLM issue? https://github.com/Stability-AI/StableLM/issues/30

The results seem unbelievably poor. It's shocking that a 7B GPT-NeoX trained on 800B tokens would score below GPT-2 700M and well below GPT-J, even if it is an early training checkpoint.

**Comment by MarkSchmidty** [comment]
Thanks!

**Comment by lhl** [comment]
You can see https://github.com/AUGMXNT/llm-experiments/blob/main/01-lm-eval.md to get an idea of how it's done. Feel free to test yourself. You'll want to use `hf-causal` as the model.
